# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('child', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('san', models.CharField(blank=True, max_length=8192, null=True)),
                ('san2', models.CharField(blank=True, max_length=8192, null=True)),
                ('santag', models.CharField(blank=True, max_length=8192, null=True)),
                ('dir', models.CharField(blank=True, max_length=8192, null=True)),
                ('note', models.CharField(blank=True, max_length=8192, null=True)),
                ('d', models.CharField(blank=True, max_length=8192, null=True)),
                ('k', models.CharField(blank=True, max_length=8192, null=True)),
                ('dnote', models.CharField(blank=True, max_length=8192, null=True)),
                ('knote', models.CharField(blank=True, max_length=8192, null=True)),
            ],
        ),
    ]
