# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotus',
            old_name='dir',
            new_name='chinese_explain',
        ),
        migrations.RenameField(
            model_name='lotus',
            old_name='san',
            new_name='sanskrit',
        ),
        migrations.RenameField(
            model_name='lotus',
            old_name='san2',
            new_name='sanskrit_eq',
        ),
        migrations.RenameField(
            model_name='lotus',
            old_name='santag',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='lotus',
            name='child',
        ),
    ]
